export const ADD_MEAL_TO_ORDER = 'ADD_MEAL_TO_ORDER';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';

export const REQUEST_MEALS_PENDING = 'REQUEST_MEALS_PENDING';
export const REQUEST_MEALS_SUCCESS = 'REQUEST_MEALS_SUCCESS';
export const REQUEST_MEALS_FAILED = 'REQUEST_MEALS_FAILED';